### ISSUE TITLE
[Regression] 89ee1ae can't use D-pad on steam client

### ISSUE THREAD

**Issue by philmmanjaro** [ShadowBlip/InputPlumber#134] opened 2024-06-28 03:48 UTC
Seems with https://github.com/ShadowBlip/InputPlumber/commit/89ee1ae427411e155c9153aef1d651f476b0b3a4 we find a regression that d-pad is not working at all. It works in OGUI overlay, however not in Steam UI. 0.25.1 has the same effect. Tested on OrangePi Neo in Xbox and DSE mode.

**Comment by pastaq** [comment] 2024-06-28 04:08
I can't reproduce this

**Comment by philmmanjaro** [comment] 2024-06-28 04:17
Currently testing if 89ee1ae427411e155c9153aef1d651f476b0b3a4 created the regression. 0.24.2 worked with the same setup.

**Comment by philmmanjaro** [comment] 2024-06-28 04:22
Reverting makes it work again ...

**Comment by pastaq** [comment] 2024-06-28 21:27
Do you have a profile you are loading that you have modified? I still can't reproduce this on any session.

**Comment by philmmanjaro** [comment] 2024-06-29 00:12
The only change we do on our end is this:

	sed -i -e 's/- ds5/- gamepad/g' ${pkgdir}/usr/share/inputplumber/devices/50-orangepi_neo.yaml
	sed -i -e 's/- ds5-edge/- gamepad/g' ${pkgdir}/usr/share/inputplumber/devices/50-rog_ally.yaml

When I revert the commit it works on the 8840u unit. Didn't had time yet to cross check the ALLY.

**Comment by pastaq** [comment] 2024-06-29 03:07
Fixed in #135

**Closed by pastaq** 2024-06-29 03:07 UTC
